### ISSUE TITLE
프론트에서 로그인 구현에 필요한 정보요청

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-BE-WEB#11]
### Description
프론트에서 로그인을 구현하면서 다음과 같은 정보들이 필요합니다. 

### API관련
- 리프레쉬 토큰으로 액세스토큰을 재발급 할 API의 패스를 알려주세요
- JWT 발급시 쿠키로 발급해주시는지, 리스폰스로 JWT넣어서 보내주시는지
- 백엔드로 요청을 보낼 때, JWT를 헤더에 넣어서 보내야하는지 쿠키에 넣어서 보내야하는지

### JWT 처리 관련
- 페이로드에 들어가는 항목
    - 카카오 ID를 포함하여 만료일, 발급자 등 페이로드에 들어가는 클레임을 알려주세요

**Comment by java-saeng** [comment]
리프레쉬 토큰으로 액세스토큰을 재발급 할 API의 패스를 알려주세요
- api 생성하고 말씀드리겠습니다

JWT 발급시 쿠키로 발급해주시는지, 리스폰스로 JWT넣어서 보내주시는지
- 리스폰스에 넣어서 보내려고 합니다

백엔드로 요청을 보낼 때, JWT를 헤더에 넣어서 보내야하는지 쿠키에 넣어서 보내야하는지
- 헤더에 보내주시면 됩니다. Authorization 헤더에 "Bearer " + [토큰] 넣어주시면 됩니다. Bearer 뒤에 공백 잊으시면 안되구요

카카오 ID를 포함하여 만료일, 발급자 등 페이로드에 들어가는 클레임을 알려주세요
- 발급날짜, 발급자(receipt), 카카오ID, aud(토큰 종류 엑세스인지 리프레쉬인지), 만료날짜, auth(유저 구분)
![image](https://user-images.githubusercontent.com/62413589/188913658-bd272833-da44-4880-a28c-2dabad45059f.png)

**Comment by mdgarden** [comment]
감사합니다! 확인했습니다~
