### ISSUE TITLE
로컬 테스트용 서버 증설

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-BE-WEB#2]
## 요약
로컬 테스트용 서버 증설

## 상세
현재 카카오톡 로그인의 환경변수가 로컬 혹은 프로덕션 하나밖에 실행할 수 없기 때문에 애로사항이 많습니다.
로컬용 서버를 증설하여 백엔드도 로컬 -> 스테이징 -> 프로덕션의 단계를 거쳐 CI/CD가 이루어졌으면 좋을 것 같습니다.
프론터가 로컬에서 테스트할 때 접속하는 백엔드 서버는 스테이징, 프론트가 프로덕션에서 접속하는 서버는 백엔드 프로덕션 서버가 되는 구조입니다.

**Comment by mdgarden** [comment]
도커 도입 검토

**Comment by jayjeong8** [comment]
이미 있는 서버의 노드 하나에 서버를 여러개 연결하는 방법(nginx를 사용해서)으로 추가로 서버를 구매하는 것 없이 해결이 될 수도 있다고 하네요! (저는 백엔드 알못이라 물어보고 왔어요)
