### ISSUE TITLE
사용자 정보를 변경, 조회 API

### ISSUE THREAD

**Issue by java-saeng** [EasyAndBeauty/DailyReceipt-BE-WEB#25]
### Description
회원가입을 한 후, 임의로 작성된 닉네임을 변경하는 API
사용자의 식별 값을 통해 정보를 조회

### Todo
- [x] 사용자 정보를 변경하는 API 추가
- [x] 사용자 정보를 조회하는 API 추가

### 비고
- 유저 닉네임 제한사항
    - 한영 상관없이 공백포함 7글자
    - 이모지가능 특수문자 가능
    - 스페이스 허용
    - 미입력 혹은 스페이스만 들어간 닉네임은 불가(null 불가)

**Comment by IGhost-P** [comment]
현재는 임시방편으로
```jsx
 const newTodos = data.filter((todo) => todo.date === newDate);
```
을 이용해 해당 날짜만 보이게 필터링을 했습니다

**Comment by mdgarden** [comment]
현재 확정된 API

| **Interface**   |  **User**        | | |
------|---|---|---|
| **id** | number | unique | user 테이블의 고유 인덱스. 모든 user는 한 테이블에 저장되며, 고유의 id를 가집니다. |
| **token_id** |   number   | unique | 토큰 식별자 값을 외래키로 가집니다. |
| **nickname**   | string | x | 유저가 우리 앱에서 설정한 닉네임입니다. |


---
Category: User

| **API Name**   |  **Get User Token**        |
------|---|
| **설명** | 카카오에서 받은 인가코드를 서버에 전하고 JWT와 기존 회원 여부를 반환합니다. |
| **Method** | GET      |  
| **Path**   | /auth/kakao/callback |
| **Params**  |  code(required, 프론트가 카카오 로그인시 받은 인가코드)  |
| **Request**   | none |   
| **Response**   | {accessToken:string(JWT), refreshToken:string(JWT), first:boolean} |
| **Auth**   | none |

| **API Name**   |  **re-issuance**        |
------|---|
| **설명** | 리프레쉬 토큰은 유효하나 액세스 토큰이 만료되었을 때, 액세스 토큰을 재발급합니다. |
| **Method** |    POST    |  
| **Path**   |  /api/v1/tokens/re-issuance  |
| **Params**  |  none  |
| **Request**   | none |   
| **Response**   | accessToken, refreshToken, isFirst(true일 경우 처음 회원가입한 회원) |
| **Auth**   | required |

| **API Name**   |  **Get User**        |
------|---|
| **설명** | 현재 유저의 정보를 취득합니다. |
| **Method** |    GET    |  
| **Path**   |  /api/v1/user/me |
| **Params**  |  none  |
| **Request**   | none |   
| **Response**   | User |
| **Auth**   | required |

| **API Name**   |  **Put User**        |
------|---|
| **설명** | 유저 정보를 수정합니다. |
| **Method** |    PUT    |  
| **Path**   |  /api/v1/user/me |
| **Params**  |  none  |
| **Request**   | User `수정할 항목만 보내도 OK. 예) {nickname : abc} / token_id는 수정 불가`  |   
| **Response**   | User |
| **Auth**   | required |

**Comment by java-saeng** [comment]
user 정보를 조회하거나 수정할 때 path를 /api/v1/user 는 어떻게 생각하시나요~
me는 뭔가 mypage 느낌이 있는 것 같아서요

**Comment by mdgarden** [comment]
좋습니당~! 패스 수정했습니다!

**Comment by java-saeng** [comment]
유저 정보를 조회할 때, 작성한 todo도 모두 반환해야하나요?

유저는 현재 닉네임, id, todoList를 가지고 있는데 어떤 걸 반환할까요?

**Comment by mdgarden** [comment]
todolist는 반환하지 않아도 될 것 같습니다! getTodoList에서 가져오면 될 것 같구
지금은 닉네임만 있어도 될 것 같아요
