### ISSUE TITLE
[Issue] date에 상관없이 모든 task가 반환됨

### ISSUE THREAD

**Issue by IGhost-P** [EasyAndBeauty/DailyReceipt-BE-WEB#26]
### Description

date에 상관없이 모든 task가 반환됨
![image](https://user-images.githubusercontent.com/79236624/192151578-301a835e-859d-4d1f-9942-ec4e458a44ac.png)
![image](https://user-images.githubusercontent.com/79236624/192151590-ea3246c8-4208-4b72-9236-f06d6f207bbe.png)

### Todo
- [ ] date에 맞게 알맞는 task 반환

**Comment by java-saeng** [comment]
url도 같이 보여주시겠어요? 제 생각에는 쿼리스트링을 date= 라고 보내신 것 같은데 API 문서를 보시면 targetDate로 되어있습니다

host/docs/index.html 을 참고해주셔서 스펙에 맞게 요청보내주시면 될 것 같아요~

**Comment by java-saeng** [comment]
![image](https://user-images.githubusercontent.com/62413589/192152716-64266d24-b9e7-4569-9f7a-f28916ba6bed.png)

**Comment by IGhost-P** [comment]
우 말대로 하니 해결 했습니다!!!
