### ISSUE TITLE
[issue] 인텔리제이 커뮤니티 버전에서 로컬 서버 구동 확인

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-BE-WEB#36]
### Description
인텔리제이 커뮤니티 버전을 사용하는 멤버들의 로컬 서버 구동 확인 및 서포트 요청

### To-Be
- 프론트 멤버들이 커뮤니티 버전을 이용해서 서버를 구동하려고 하는데 얼티메이트판과 인터페이스가 다소 달라서 세팅에 어려움이 있었습니다. 언제 한번 날 잡아서 세팅 도와주시면 감사하겠습니다.
- 저번에 저랑 댄 세팅해주시면서 도커는 더 필요없다고 말씀하셨는데, 서버 자체를 도커에서 구동하지 않는다는 뜻이었을까요? 데이터베이스는 여전히 도커에서 실행할 필요가 있는 걸로 이해하고 있는데 제가 생각하고 있는게 맞을까요?

### Todo
- [ ] 레몬
- [ ] 블루
- [ ] 제이

**Comment by java-saeng** [comment]
궁금한 점
- 마당과 댄은 community 버젼이 아닌건가요??

해결 방법
1. 터미널에서 mysql을 띄우기 위해 `docker run -d -p 3306:3306 --env MYSQL_DATABASE=receipt --env MYSQL_ROOT_PASSWORD=1234 --platform linux/amd64 mysql:8.0.28` 를 해줍니다 ( mac m1 이 아닐 경우에는 "linux/amd64"를 빼주시면 됩니다)
2. 인텔리제이에서 플젝을 pull 받습니다
3.  edit configuration 들어갑니다
![image](https://user-images.githubusercontent.com/62413589/195113323-7fc5afad-f52b-4f55-be5a-e3e71b4301cf.png)
4. 네모친 부분을 똑같이 해주세요
![image](https://user-images.githubusercontent.com/62413589/195113599-8dcb44df-f7ad-4034-b1d0-87a1e1ecc0f4.png)
5.  재생 눌러줍니다
![image](https://user-images.githubusercontent.com/62413589/195114155-d1016508-0afc-49fd-851c-768e5f0a5a1d.png)

**Comment by java-saeng** [comment]
@mdgarden  저도 community 버젼을 사용해본 적이 없어서 혹시 ultimate 랑 어느 점이 좀 다른가요,,

**Comment by mdgarden** [comment]
Active Profiles 입력하는 란이 없었습니다...ㅠ
글고 롬복 다운로드도 다 수동으로 해야하더라구요 ㅋㅋㅋㅋ ㅠㅠㅠ.....
어째저째 검색해서 커뮤니티판에서 local로 실행시키는 방법이랑 스프링 실행시키는 방법 찾아서 하긴 했는데 잘 된건지 확신할 수가 없네요 🤔
mysql 도커에서 실행하는 부분 다시 해보고 또 에러 생기면 그 때 구체적인 에러 메세지랑 같이 코멘트 남겨두겠습니당!
