### ISSUE TITLE
영수증 POST API 수정 요청

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-BE-WEB#39]
### Description
POST Receipt API의 리스폰스값을 수정부탁드립니다.

### To-Be
- [x] POST로 생성된 영수증의 id값을 포함한 receipt 전체를 리스폰스로 반환

기존 POST에서는 status만 받기로 했었는데, 제가 미처 생각하지 못한 부분이 있어 수정이 필요합니다. POST로 생성된 이후의 해당 영수증의 id값을포함한 receipt 전체를  리스폰스로 받을 수 있도록 수정해주시면 감사하겠습니다. API 문서도 수정해두었으니 참고 부탁드립니다.

https://github.com/EasyAndBeauty/DailyReceipt-BE-WEB/wiki/API-%EB%AC%B8%EC%84%9C#receipt

**Comment by java-saeng** [comment]
혹시 이전 명세는 삭제하셨을까요? 어느 부분이 변경된건지 궁금해서요 !

**Comment by java-saeng** [comment]
답변 늦어서 죄송합니다,,!

POST 시 id 뿐만 아니라 저장된 값들을 모두 반환해달라는 말씀이신가요?? 기존에는 id 만 반환했습니다

**Comment by mdgarden** [comment]
네 맞습니다 id 포함해서 모두 반환 부탁드립니다!
기존에 id만 반환하는건 몰랐네요 문서를 쓰다 말았나 ㅠ...아무튼 모두 반환하도록 수정 부탁드리겠습니다.
